name: Monitoring API Open Source

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Executa todo dia às 12hrs

jobs:
  monitoring:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and run Dcoker Container
      run: | 
          docker build -t api-monitor .
          docker run -d --name api-monitor-container -p 5000:5000 api-monitor
          sleep 5
    
    - name: Fetch monitoring results
      run: | 
          curl http://localhost:5000/monitor -o results.json
          cat results.json

    - name: Install Python dependencies
      run: pip install requests
        
    - name: Format and send results to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python send_to_discord.py
        
